# Generated by Django 3.2.9 on 2021-11-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaPublicitaria',
            fields=[
                ('IdCampania', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_CampPub', models.CharField(max_length=40)),
                ('Descripcion_CampPub', models.CharField(max_length=100)),
                ('Precio_CampPub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ListaMediosEmision', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaProductos',
            fields=[
                ('IdOfertaProd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_OferProd', models.CharField(max_length=40)),
                ('ListaProductos', models.CharField(max_length=100)),
                ('Precio_OferProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaIni_OferProd', models.DateField()),
                ('FechaFin_OferProd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Promociona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCampania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaniapublicitaria')),
                ('IdOfertaProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ofertaproductos')),
            ],
        ),
    ]
