# Generated by Django 3.2.9 on 2021-11-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('IDOfertaEmpleo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('ListadoEmpleos', models.CharField(max_length=100)),
                ('FechaIni_OferEmp', models.DateField()),
                ('FechaFin_OferEmp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre_Empleado', models.CharField(max_length=30)),
                ('Tlf_Empleado', models.IntegerField()),
                ('NumSegSocial', models.IntegerField()),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDOfertaEmpleo', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.CASCADE, to='rrhh.ofertaempleo')),
            ],
        ),
    ]
