# Generated by Django 3.2.9 on 2021-11-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('rrhh', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeCuentas',
            fields=[
                ('IdInforme', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Fecha_Informe', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InformePOS',
            fields=[
                ('IdInforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas')),
                ('BeneficiosPOS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CodigoPOS', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='InformeTributario',
            fields=[
                ('IdInforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas')),
                ('ImporteTributario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InformeSalarialEmpleado',
            fields=[
                ('IdInforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas')),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='InformeProveedor',
            fields=[
                ('IdInforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas')),
                ('NumProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='InformeCampania',
            fields=[
                ('IdInforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas')),
                ('IdCampania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaniapublicitaria')),
            ],
        ),
    ]
