# Generated by Django 3.2.9 on 2021-11-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informepos',
            name='IdPOS',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='informecampania',
            name='IdInforme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas'),
        ),
        migrations.AlterField(
            model_name='informepos',
            name='IdInforme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas'),
        ),
        migrations.AlterField(
            model_name='informeproveedor',
            name='IdInforme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas'),
        ),
        migrations.AlterField(
            model_name='informesalarialempleado',
            name='IdInforme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas'),
        ),
        migrations.AlterField(
            model_name='informetributario',
            name='IdInforme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.informecuentas'),
        ),
    ]
