# Generated by Django 3.2.9 on 2021-11-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('NumProveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Prov', models.CharField(max_length=40)),
                ('DireccionWeb_Prov', models.CharField(max_length=20)),
                ('Tlf_Prov', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('NumPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('Articulos', models.CharField(max_length=200)),
                ('Fecha_Ped', models.DateField()),
                ('Precio_Ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
                ('NumProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.proveedor')),
            ],
        ),
    ]
