# Generated by Django 3.2.9 on 2021-11-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('IdAlmacen', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Direccion_Alm', models.CharField(max_length=50)),
                ('Superficie', models.CharField(max_length=10)),
                ('FechaIniAlquiler_Alm', models.DateField()),
                ('FechaFinAlquiler_Alm', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteProductos',
            fields=[
                ('IdLote', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Descripcion_Lote', models.TextField(blank=True, null=True)),
                ('Unidad', models.CharField(max_length=20)),
                ('Cantidad_Lote', models.IntegerField()),
                ('Coste_Lote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
            ],
        ),
    ]
